/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ComparisonPatientIdRouteImport } from './routes/comparison.$patientId'
import { Route as ExaminationsIndexRouteImport } from './routes/examinations.index'
import { Route as ExaminationsNewRouteImport } from './routes/examinations.new'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientsNewRouteImport } from './routes/patients.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonPatientIdRoute = ComparisonPatientIdRouteImport.update({
  id: '/comparison/$patientId',
  path: '/comparison/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsIndexRoute = ExaminationsIndexRouteImport.update({
  id: '/examinations/',
  path: '/examinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsNewRoute = ExaminationsNewRouteImport.update({
  id: '/examinations/new',
  path: '/examinations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/comparison/$patientId': typeof ComparisonPatientIdRoute
  '/examinations/new': typeof ExaminationsNewRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/examinations/': typeof ExaminationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/comparison/$patientId': typeof ComparisonPatientIdRoute
  '/examinations/new': typeof ExaminationsNewRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/examinations': typeof ExaminationsIndexRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/comparison/$patientId': typeof ComparisonPatientIdRoute
  '/examinations/new': typeof ExaminationsNewRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/examinations/': typeof ExaminationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/settings'
    | '/comparison/$patientId'
    | '/examinations/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/examinations/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/settings'
    | '/comparison/$patientId'
    | '/examinations/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/examinations'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/settings'
    | '/comparison/$patientId'
    | '/examinations/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/examinations/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  ComparisonPatientIdRoute: typeof ComparisonPatientIdRoute
  ExaminationsNewRoute: typeof ExaminationsNewRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  ExaminationsIndexRoute: typeof ExaminationsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/$patientId': {
      id: '/comparison/$patientId'
      path: '/comparison/$patientId'
      fullPath: '/comparison/$patientId'
      preLoaderRoute: typeof ComparisonPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations/': {
      id: '/examinations/'
      path: '/examinations'
      fullPath: '/examinations/'
      preLoaderRoute: typeof ExaminationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations/new': {
      id: '/examinations/new'
      path: '/examinations/new'
      fullPath: '/examinations/new'
      preLoaderRoute: typeof ExaminationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  ComparisonPatientIdRoute: ComparisonPatientIdRoute,
  ExaminationsNewRoute: ExaminationsNewRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  ExaminationsIndexRoute: ExaminationsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
